name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"  # كل 12 ساعة
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Generate pacman contribution graph
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: "mohamed-sheta"  # ضع اسم المستخدم هنا

      # 3️⃣ Push generated SVG to output branch
      - name: Push pacman-contribution-graph.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .   # "." لو SVG تولد في root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
